/* Generated by Yosys 0.45+139 (git sha1 4d581a97d, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* top =  1  *)
(* src = "./hdl/behavioral_parkingController.v:3.1-122.10" *)
module behavioral_parkingController(vehicle_arrival, code, vehicle_left, clk, rst, code_ack, gate_ack, open_gate, wrong_ping, close_gate, blocked_gate);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  (* src = "./hdl/behavioral_parkingController.v:25.17-25.24" *)
  wire [1:0] attempt;
  (* src = "./hdl/behavioral_parkingController.v:18.25-18.37" *)
  output blocked_gate;
  wire blocked_gate;
  (* src = "./hdl/behavioral_parkingController.v:9.25-9.28" *)
  input clk;
  wire clk;
  (* src = "./hdl/behavioral_parkingController.v:17.25-17.35" *)
  output close_gate;
  wire close_gate;
  (* src = "./hdl/behavioral_parkingController.v:7.25-7.29" *)
  input [15:0] code;
  wire [15:0] code;
  (* src = "./hdl/behavioral_parkingController.v:11.25-11.33" *)
  input code_ack;
  wire code_ack;
  (* src = "./hdl/behavioral_parkingController.v:12.25-12.33" *)
  input gate_ack;
  wire gate_ack;
  (* src = "./hdl/behavioral_parkingController.v:15.25-15.34" *)
  output open_gate;
  wire open_gate;
  (* src = "./hdl/behavioral_parkingController.v:10.25-10.28" *)
  input rst;
  wire rst;
  (* src = "./hdl/behavioral_parkingController.v:21.17-21.22" *)
  wire [5:0] state;
  (* src = "./hdl/behavioral_parkingController.v:6.25-6.40" *)
  input vehicle_arrival;
  wire vehicle_arrival;
  (* src = "./hdl/behavioral_parkingController.v:8.25-8.37" *)
  input vehicle_left;
  wire vehicle_left;
  (* src = "./hdl/behavioral_parkingController.v:16.25-16.35" *)
  output wrong_ping;
  wire wrong_ping;
  NOT _106_ (
    .A(state[5]),
    .Y(_053_)
  );
  NOT _107_ (
    .A(state[4]),
    .Y(_054_)
  );
  NOT _108_ (
    .A(state[3]),
    .Y(_055_)
  );
  NOT _109_ (
    .A(state[2]),
    .Y(_056_)
  );
  NOT _110_ (
    .A(state[1]),
    .Y(_057_)
  );
  NOT _111_ (
    .A(state[0]),
    .Y(_058_)
  );
  NOT _112_ (
    .A(attempt[1]),
    .Y(_059_)
  );
  NOT _113_ (
    .A(attempt[0]),
    .Y(_060_)
  );
  NOT _114_ (
    .A(rst),
    .Y(_061_)
  );
  NOT _115_ (
    .A(code_ack),
    .Y(_062_)
  );
  NOT _116_ (
    .A(vehicle_arrival),
    .Y(_063_)
  );
  NOR _117_ (
    .A(state[3]),
    .B(state[2]),
    .Y(_064_)
  );
  NOR _118_ (
    .A(state[5]),
    .B(state[4]),
    .Y(_065_)
  );
  NAND _119_ (
    .A(_064_),
    .B(_065_),
    .Y(_066_)
  );
  NAND _120_ (
    .A(state[1]),
    .B(_058_),
    .Y(_067_)
  );
  NOR _121_ (
    .A(_066_),
    .B(_067_),
    .Y(_068_)
  );
  NOR _122_ (
    .A(state[1]),
    .B(state[0]),
    .Y(_069_)
  );
  NAND _123_ (
    .A(_055_),
    .B(_069_),
    .Y(_070_)
  );
  NOR _124_ (
    .A(state[2]),
    .B(_070_),
    .Y(_071_)
  );
  NOR _125_ (
    .A(state[5]),
    .B(_054_),
    .Y(_072_)
  );
  NAND _126_ (
    .A(_071_),
    .B(_072_),
    .Y(_073_)
  );
  NOT _127_ (
    .A(_073_),
    .Y(close_gate)
  );
  NOR _128_ (
    .A(_053_),
    .B(state[4]),
    .Y(_074_)
  );
  NAND _129_ (
    .A(_071_),
    .B(_074_),
    .Y(_075_)
  );
  NOT _130_ (
    .A(_075_),
    .Y(_076_)
  );
  NAND _131_ (
    .A(_057_),
    .B(state[0]),
    .Y(_077_)
  );
  NOR _132_ (
    .A(_066_),
    .B(_077_),
    .Y(_078_)
  );
  NOR _133_ (
    .A(_068_),
    .B(_078_),
    .Y(_079_)
  );
  NAND _134_ (
    .A(_073_),
    .B(_079_),
    .Y(_080_)
  );
  NOR _135_ (
    .A(_076_),
    .B(_080_),
    .Y(_081_)
  );
  NAND _136_ (
    .A(_065_),
    .B(_069_),
    .Y(_082_)
  );
  NAND _137_ (
    .A(_055_),
    .B(state[2]),
    .Y(_083_)
  );
  NOR _138_ (
    .A(_082_),
    .B(_083_),
    .Y(_084_)
  );
  NAND _139_ (
    .A(code_ack),
    .B(_084_),
    .Y(_085_)
  );
  NAND _140_ (
    .A(_081_),
    .B(_085_),
    .Y(_086_)
  );
  NOR _141_ (
    .A(_060_),
    .B(_086_),
    .Y(_087_)
  );
  NAND _142_ (
    .A(_062_),
    .B(_084_),
    .Y(_088_)
  );
  NAND _143_ (
    .A(_060_),
    .B(_088_),
    .Y(_089_)
  );
  NAND _144_ (
    .A(_061_),
    .B(_089_),
    .Y(_090_)
  );
  NOR _145_ (
    .A(_087_),
    .B(_090_),
    .Y(_000_)
  );
  NOR _146_ (
    .A(_059_),
    .B(_060_),
    .Y(_091_)
  );
  NAND _147_ (
    .A(attempt[1]),
    .B(attempt[0]),
    .Y(_092_)
  );
  NOR _148_ (
    .A(_088_),
    .B(_091_),
    .Y(_093_)
  );
  NOR _149_ (
    .A(_086_),
    .B(_093_),
    .Y(_094_)
  );
  NOR _150_ (
    .A(_060_),
    .B(_088_),
    .Y(_095_)
  );
  NOR _151_ (
    .A(attempt[1]),
    .B(_095_),
    .Y(_096_)
  );
  NOR _152_ (
    .A(rst),
    .B(_096_),
    .Y(_097_)
  );
  NOT _153_ (
    .A(_097_),
    .Y(_098_)
  );
  NOR _154_ (
    .A(_094_),
    .B(_098_),
    .Y(_001_)
  );
  NAND _155_ (
    .A(state[3]),
    .B(_056_),
    .Y(_099_)
  );
  NOR _156_ (
    .A(_082_),
    .B(_099_),
    .Y(open_gate)
  );
  NOR _157_ (
    .A(_084_),
    .B(open_gate),
    .Y(_100_)
  );
  NAND _158_ (
    .A(_081_),
    .B(_100_),
    .Y(_101_)
  );
  NAND _159_ (
    .A(gate_ack),
    .B(close_gate),
    .Y(_102_)
  );
  NAND _160_ (
    .A(_063_),
    .B(_078_),
    .Y(_103_)
  );
  NAND _161_ (
    .A(_102_),
    .B(_103_),
    .Y(_104_)
  );
  NOR _162_ (
    .A(rst),
    .B(_104_),
    .Y(_105_)
  );
  NAND _163_ (
    .A(_101_),
    .B(_105_),
    .Y(_002_)
  );
  NAND _164_ (
    .A(vehicle_arrival),
    .B(_078_),
    .Y(_008_)
  );
  NOR _165_ (
    .A(code_ack),
    .B(vehicle_left),
    .Y(_009_)
  );
  NAND _166_ (
    .A(_068_),
    .B(_009_),
    .Y(_010_)
  );
  NAND _167_ (
    .A(_008_),
    .B(_010_),
    .Y(_011_)
  );
  NOR _168_ (
    .A(_093_),
    .B(_011_),
    .Y(_012_)
  );
  NOR _169_ (
    .A(rst),
    .B(_012_),
    .Y(_003_)
  );
  NOR _170_ (
    .A(rst),
    .B(_085_),
    .Y(_013_)
  );
  NOT _171_ (
    .A(_013_),
    .Y(_014_)
  );
  NOR _172_ (
    .A(rst),
    .B(vehicle_left),
    .Y(_015_)
  );
  NOT _173_ (
    .A(_015_),
    .Y(_016_)
  );
  NAND _174_ (
    .A(code_ack),
    .B(_068_),
    .Y(_017_)
  );
  NOR _175_ (
    .A(_016_),
    .B(_017_),
    .Y(_018_)
  );
  NAND _176_ (
    .A(code[12]),
    .B(code[14]),
    .Y(_019_)
  );
  NOT _177_ (
    .A(_019_),
    .Y(_020_)
  );
  NOR _178_ (
    .A(code[0]),
    .B(code[1]),
    .Y(_021_)
  );
  NOT _179_ (
    .A(_021_),
    .Y(_022_)
  );
  NOR _180_ (
    .A(_019_),
    .B(_022_),
    .Y(_023_)
  );
  NAND _181_ (
    .A(_020_),
    .B(_021_),
    .Y(_024_)
  );
  NAND _182_ (
    .A(code[4]),
    .B(code[7]),
    .Y(_025_)
  );
  NAND _183_ (
    .A(code[8]),
    .B(code[11]),
    .Y(_026_)
  );
  NOR _184_ (
    .A(_025_),
    .B(_026_),
    .Y(_027_)
  );
  NOT _185_ (
    .A(_027_),
    .Y(_028_)
  );
  NOR _186_ (
    .A(_024_),
    .B(_028_),
    .Y(_029_)
  );
  NAND _187_ (
    .A(_023_),
    .B(_027_),
    .Y(_030_)
  );
  NOR _188_ (
    .A(code[9]),
    .B(code[10]),
    .Y(_031_)
  );
  NOR _189_ (
    .A(code[13]),
    .B(code[15]),
    .Y(_032_)
  );
  NAND _190_ (
    .A(_031_),
    .B(_032_),
    .Y(_033_)
  );
  NOR _191_ (
    .A(code[2]),
    .B(code[3]),
    .Y(_034_)
  );
  NOR _192_ (
    .A(code[5]),
    .B(code[6]),
    .Y(_035_)
  );
  NAND _193_ (
    .A(_034_),
    .B(_035_),
    .Y(_036_)
  );
  NOR _194_ (
    .A(_033_),
    .B(_036_),
    .Y(_037_)
  );
  NOT _195_ (
    .A(_037_),
    .Y(_038_)
  );
  NOR _196_ (
    .A(_030_),
    .B(_038_),
    .Y(_039_)
  );
  NAND _197_ (
    .A(_029_),
    .B(_037_),
    .Y(_040_)
  );
  NAND _198_ (
    .A(_018_),
    .B(_040_),
    .Y(_041_)
  );
  NAND _199_ (
    .A(_014_),
    .B(_041_),
    .Y(_004_)
  );
  NAND _200_ (
    .A(open_gate),
    .B(_015_),
    .Y(_042_)
  );
  NAND _201_ (
    .A(_018_),
    .B(_039_),
    .Y(_043_)
  );
  NAND _202_ (
    .A(_042_),
    .B(_043_),
    .Y(_005_)
  );
  NOR _203_ (
    .A(gate_ack),
    .B(_073_),
    .Y(_044_)
  );
  NAND _204_ (
    .A(vehicle_left),
    .B(open_gate),
    .Y(_045_)
  );
  NOT _205_ (
    .A(_045_),
    .Y(_046_)
  );
  NOR _206_ (
    .A(vehicle_arrival),
    .B(_045_),
    .Y(_047_)
  );
  NOR _207_ (
    .A(_044_),
    .B(_047_),
    .Y(_048_)
  );
  NOR _208_ (
    .A(rst),
    .B(_048_),
    .Y(_006_)
  );
  NOR _209_ (
    .A(_088_),
    .B(_092_),
    .Y(_049_)
  );
  NAND _210_ (
    .A(vehicle_arrival),
    .B(_046_),
    .Y(_050_)
  );
  NAND _211_ (
    .A(_075_),
    .B(_050_),
    .Y(_051_)
  );
  NOR _212_ (
    .A(_049_),
    .B(_051_),
    .Y(_052_)
  );
  NOR _213_ (
    .A(rst),
    .B(_052_),
    .Y(_007_)
  );
  NOR _214_ (
    .A(_075_),
    .B(_091_),
    .Y(blocked_gate)
  );
  NOR _215_ (
    .A(_075_),
    .B(_092_),
    .Y(wrong_ping)
  );
  (* src = "./hdl/behavioral_parkingController.v:32.5-43.8" *)
  DFF _216_ (
    .C(clk),
    .D(_000_),
    .Q(attempt[0])
  );
  (* src = "./hdl/behavioral_parkingController.v:32.5-43.8" *)
  DFF _217_ (
    .C(clk),
    .D(_001_),
    .Q(attempt[1])
  );
  (* src = "./hdl/behavioral_parkingController.v:32.5-43.8" *)
  DFF _218_ (
    .C(clk),
    .D(_002_),
    .Q(state[0])
  );
  (* src = "./hdl/behavioral_parkingController.v:32.5-43.8" *)
  DFF _219_ (
    .C(clk),
    .D(_003_),
    .Q(state[1])
  );
  (* src = "./hdl/behavioral_parkingController.v:32.5-43.8" *)
  DFF _220_ (
    .C(clk),
    .D(_004_),
    .Q(state[2])
  );
  (* src = "./hdl/behavioral_parkingController.v:32.5-43.8" *)
  DFF _221_ (
    .C(clk),
    .D(_005_),
    .Q(state[3])
  );
  (* src = "./hdl/behavioral_parkingController.v:32.5-43.8" *)
  DFF _222_ (
    .C(clk),
    .D(_006_),
    .Q(state[4])
  );
  (* src = "./hdl/behavioral_parkingController.v:32.5-43.8" *)
  DFF _223_ (
    .C(clk),
    .D(_007_),
    .Q(state[5])
  );
endmodule
