/* Generated by Yosys 0.45+139 (git sha1 4d581a97d, clang++ 14.0.0-1ubuntu1.1 -fPIC -O3) */

(* top =  1  *)
(* src = "./hdl/behavioral_parkingController.v:3.1-122.10" *)
module behavioral_parkingController(vehicle_arrival, code, vehicle_left, clk, rst, code_ack, gate_ack, open_gate, wrong_ping, close_gate, blocked_gate);
  (* src = "./hdl/behavioral_parkingController.v:45.5-121.8" *)
  wire _000_;
  (* src = "./hdl/behavioral_parkingController.v:45.5-121.8" *)
  wire _001_;
  (* src = "./hdl/behavioral_parkingController.v:45.5-121.8" *)
  wire [5:0] _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire [7:0] _031_;
  wire [3:0] _032_;
  wire [1:0] _033_;
  wire [1:0] _034_;
  wire [2:0] _035_;
  wire _036_;
  wire [2:0] _037_;
  wire _038_;
  wire [2:0] _039_;
  wire _040_;
  wire [2:0] _041_;
  wire _042_;
  wire _043_;
  wire [2:0] _044_;
  wire _045_;
  wire [2:0] _046_;
  wire [2:0] _047_;
  wire _048_;
  wire [2:0] _049_;
  wire _050_;
  wire [2:0] _051_;
  wire _052_;
  wire [2:0] _053_;
  wire _054_;
  wire [2:0] _055_;
  wire [2:0] _056_;
  wire _057_;
  wire _058_;
  wire [2:0] _059_;
  wire _060_;
  wire _061_;
  (* src = "./hdl/behavioral_parkingController.v:66.35-66.55" *)
  wire _062_;
  (* force_downto = 32'd1 *)
  (* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:571.28-571.29" *)
  wire [3:0] _063_;
  (* force_downto = 32'd1 *)
  (* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:583.28-583.35" *)
  wire [3:0] _064_;
  (* force_downto = 32'd1 *)
  (* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:573.22-573.23" *)
  wire [1:0] _065_;
  (* force_downto = 32'd1 *)
  (* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:571.28-571.29" *)
  wire [35:0] _066_;
  (* force_downto = 32'd1 *)
  (* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:583.28-583.35" *)
  wire [35:0] _067_;
  (* force_downto = 32'd1 *)
  (* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:573.22-573.23" *)
  wire [5:0] _068_;
  (* force_downto = 32'd1 *)
  (* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:578.19-578.22" *)
  wire [5:0] _069_;
  (* force_downto = 32'd1 *)
  (* src = "./hdl/behavioral_parkingController.v:78.43-78.58|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:270.23-270.24" *)
  wire [1:0] _070_;
  (* force_downto = 32'd1 *)
  (* src = "./hdl/behavioral_parkingController.v:78.43-78.58|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:270.26-270.27" *)
  wire [1:0] _071_;
  (* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.15" *)
  wire _072_;
  (* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.15" *)
  wire _073_;
  (* src = "./hdl/behavioral_parkingController.v:92.34-92.69" *)
  wire [5:0] _074_;
  (* src = "./hdl/behavioral_parkingController.v:25.17-25.24" *)
  reg [1:0] attempt;
  (* src = "./hdl/behavioral_parkingController.v:18.25-18.37" *)
  output blocked_gate;
  wire blocked_gate;
  (* src = "./hdl/behavioral_parkingController.v:9.25-9.28" *)
  input clk;
  wire clk;
  (* src = "./hdl/behavioral_parkingController.v:17.25-17.35" *)
  output close_gate;
  wire close_gate;
  (* src = "./hdl/behavioral_parkingController.v:7.25-7.29" *)
  input [15:0] code;
  wire [15:0] code;
  (* src = "./hdl/behavioral_parkingController.v:11.25-11.33" *)
  input code_ack;
  wire code_ack;
  (* src = "./hdl/behavioral_parkingController.v:12.25-12.33" *)
  input gate_ack;
  wire gate_ack;
  (* src = "./hdl/behavioral_parkingController.v:26.17-26.29" *)
  wire [1:0] next_attempt;
  (* src = "./hdl/behavioral_parkingController.v:22.17-22.27" *)
  wire [5:0] next_state;
  (* src = "./hdl/behavioral_parkingController.v:15.25-15.34" *)
  output open_gate;
  wire open_gate;
  (* src = "./hdl/behavioral_parkingController.v:10.25-10.28" *)
  input rst;
  wire rst;
  (* src = "./hdl/behavioral_parkingController.v:21.17-21.22" *)
  reg [5:0] state;
  (* src = "./hdl/behavioral_parkingController.v:6.25-6.40" *)
  input vehicle_arrival;
  wire vehicle_arrival;
  (* src = "./hdl/behavioral_parkingController.v:8.25-8.37" *)
  input vehicle_left;
  wire vehicle_left;
  (* src = "./hdl/behavioral_parkingController.v:16.25-16.35" *)
  output wrong_ping;
  wire wrong_ping;
  (* src = "./hdl/behavioral_parkingController.v:32.5-43.8" *)
  always @(posedge clk)
    if (rst) attempt[0] <= 1'h0;
    else if (_010_) attempt[0] <= next_attempt[0];
  (* src = "./hdl/behavioral_parkingController.v:32.5-43.8" *)
  always @(posedge clk)
    if (rst) attempt[1] <= 1'h0;
    else if (_010_) attempt[1] <= next_attempt[1];
  (* src = "./hdl/behavioral_parkingController.v:32.5-43.8" *)
  always @(posedge clk)
    if (rst) state[0] <= 1'h1;
    else if (_011_) state[0] <= next_state[0];
  (* src = "./hdl/behavioral_parkingController.v:32.5-43.8" *)
  always @(posedge clk)
    if (rst) state[1] <= 1'h0;
    else if (_011_) state[1] <= next_state[1];
  (* src = "./hdl/behavioral_parkingController.v:32.5-43.8" *)
  always @(posedge clk)
    if (rst) state[2] <= 1'h0;
    else if (_011_) state[2] <= next_state[2];
  (* src = "./hdl/behavioral_parkingController.v:32.5-43.8" *)
  always @(posedge clk)
    if (rst) state[3] <= 1'h0;
    else if (_011_) state[3] <= next_state[3];
  (* src = "./hdl/behavioral_parkingController.v:32.5-43.8" *)
  always @(posedge clk)
    if (rst) state[4] <= 1'h0;
    else if (_011_) state[4] <= next_state[4];
  (* src = "./hdl/behavioral_parkingController.v:32.5-43.8" *)
  always @(posedge clk)
    if (rst) state[5] <= 1'h0;
    else if (_011_) state[5] <= next_state[5];
  assign _012_ = ~code[4];
  assign _013_ = ~code[7];
  assign _014_ = ~code[8];
  assign _015_ = ~code[11];
  assign _016_ = ~code[12];
  assign _017_ = ~code[14];
  assign _070_[0] = ~attempt[0];
  assign _018_ = ~attempt[1];
  assign _019_ = ~state[5];
  assign _020_ = ~state[2];
  assign _021_ = ~state[4];
  assign _022_ = ~state[1];
  assign _023_ = ~state[0];
  assign _024_ = ~state[3];
  assign _029_ = ~code_ack;
  assign _031_[0] = code[0] |(* src = "./hdl/behavioral_parkingController.v:66.35-66.55" *)  code[1];
  assign _031_[1] = code[2] |(* src = "./hdl/behavioral_parkingController.v:66.35-66.55" *)  code[3];
  assign _031_[2] = _012_ |(* src = "./hdl/behavioral_parkingController.v:66.35-66.55" *)  code[5];
  assign _031_[3] = code[6] |(* src = "./hdl/behavioral_parkingController.v:66.35-66.55" *)  _013_;
  assign _031_[4] = _014_ |(* src = "./hdl/behavioral_parkingController.v:66.35-66.55" *)  code[9];
  assign _031_[5] = code[10] |(* src = "./hdl/behavioral_parkingController.v:66.35-66.55" *)  _015_;
  assign _031_[6] = _016_ |(* src = "./hdl/behavioral_parkingController.v:66.35-66.55" *)  code[13];
  assign _031_[7] = _017_ |(* src = "./hdl/behavioral_parkingController.v:66.35-66.55" *)  code[15];
  assign _032_[0] = _031_[0] |(* src = "./hdl/behavioral_parkingController.v:66.35-66.55" *)  _031_[1];
  assign _032_[1] = _031_[2] |(* src = "./hdl/behavioral_parkingController.v:66.35-66.55" *)  _031_[3];
  assign _032_[2] = _031_[4] |(* src = "./hdl/behavioral_parkingController.v:66.35-66.55" *)  _031_[5];
  assign _032_[3] = _031_[6] |(* src = "./hdl/behavioral_parkingController.v:66.35-66.55" *)  _031_[7];
  assign _033_[0] = _032_[0] |(* src = "./hdl/behavioral_parkingController.v:66.35-66.55" *)  _032_[1];
  assign _033_[1] = _032_[2] |(* src = "./hdl/behavioral_parkingController.v:66.35-66.55" *)  _032_[3];
  assign _061_ = _033_[0] |(* src = "./hdl/behavioral_parkingController.v:66.35-66.55" *)  _033_[1];
  assign _000_ = _070_[0] |(* src = "./hdl/behavioral_parkingController.v:106.22-106.38" *)  _018_;
  assign _034_[0] = _068_[0] |(* src = {0{1'b0}} *)  close_gate;
  assign _065_[0] = _034_[0] |(* src = {0{1'b0}} *)  _034_[1];
  assign _035_[0] = _009_ &(* src = {0{1'b0}} *)  _008_;
  assign _035_[1] = _007_ &(* src = {0{1'b0}} *)  _006_;
  assign _035_[2] = _005_ &(* src = {0{1'b0}} *)  _003_;
  assign _036_ = _035_[0] &(* src = {0{1'b0}} *)  _035_[1];
  assign _011_ = _036_ &(* src = {0{1'b0}} *)  _035_[2];
  assign _008_ = gate_ack |(* src = {0{1'b0}} *)  _025_;
  assign _037_[1] = _020_ |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16" *)  state[3];
  assign _038_ = _037_[0] |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16" *)  _037_[1];
  assign _030_ = _038_ |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16" *)  _037_[2];
  assign _039_[0] = state[0] |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16" *)  _022_;
  assign _040_ = _039_[0] |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16" *)  _039_[1];
  assign _027_ = _040_ |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16" *)  _037_[2];
  assign _007_ = vehicle_left |(* src = {0{1'b0}} *)  _026_;
  assign _041_[0] = _023_ |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16" *)  state[1];
  assign _042_ = _041_[0] |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16" *)  _039_[1];
  assign _028_ = _042_ |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16" *)  _037_[2];
  assign _043_ = vehicle_left |(* src = {0{1'b0}} *)  code_ack;
  assign _006_ = _043_ |(* src = {0{1'b0}} *)  _027_;
  assign _044_[2] = _021_ |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16" *)  state[5];
  assign _025_ = _045_ |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16" *)  _044_[2];
  assign _005_ = vehicle_arrival |(* src = {0{1'b0}} *)  _028_;
  assign _037_[0] = state[0] |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16" *)  state[1];
  assign _039_[1] = state[2] |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16" *)  state[3];
  assign _046_[2] = state[4] |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16" *)  _019_;
  assign _045_ = _037_[0] |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16" *)  _039_[1];
  assign _009_ = _045_ |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16" *)  _046_[2];
  assign _010_ = _004_ &(* src = {0{1'b0}} *)  _003_;
  assign _047_[1] = state[2] |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16" *)  _024_;
  assign _037_[2] = state[4] |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16" *)  state[5];
  assign _048_ = _037_[0] |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16" *)  _047_[1];
  assign _026_ = _048_ |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16" *)  _037_[2];
  assign _003_ = _029_ |(* src = {0{1'b0}} *)  _030_;
  assign _049_[1] = _067_[17] |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _067_[23];
  assign _050_ = _067_[11] |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _049_[1];
  assign _069_[5] = _050_ |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _049_[2];
  assign _051_[1] = _067_[16] |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _067_[22];
  assign _052_ = _067_[11] |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _051_[1];
  assign _069_[4] = _052_ |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _049_[2];
  assign _053_[2] = _067_[27] |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _067_[35];
  assign _069_[3] = _054_ |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _053_[2];
  assign _053_[1] = _067_[15] |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _067_[22];
  assign _055_[2] = _067_[26] |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _067_[35];
  assign _054_ = _067_[11] |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _053_[1];
  assign _069_[2] = _054_ |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _055_[2];
  assign _056_[1] = _067_[15] |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _067_[19];
  assign _056_[2] = _067_[29] |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _067_[31];
  assign _057_ = _067_[11] |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _056_[1];
  assign _069_[1] = _057_ |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _056_[2];
  assign _049_[2] = _067_[29] |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _067_[35];
  assign _058_ = _067_[6] |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _053_[1];
  assign _069_[0] = _058_ |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:593.20-593.31" *)  _049_[2];
  assign _059_[1] = open_gate |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.15" *)  _065_[1];
  assign _034_[1] = _068_[4] |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.15" *)  _068_[5];
  assign _060_ = _034_[0] |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.15" *)  _059_[1];
  assign _073_ = _060_ |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.15" *)  _034_[1];
  assign _072_ = _065_[0] |(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.15" *)  _065_[1];
  assign _001_ = ~(* src = "./hdl/behavioral_parkingController.v:106.22-106.38" *) _000_;
  assign _065_[1] = ~(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16" *) _030_;
  assign _068_[4] = ~(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16" *) _027_;
  assign _068_[5] = ~(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16" *) _028_;
  assign _068_[0] = ~(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16" *) _009_;
  assign _062_ = ~(* src = "./hdl/behavioral_parkingController.v:66.34-66.74" *) _061_;
  assign _074_[4] = ~(* src = "./hdl/behavioral_parkingController.v:92.34-92.69" *) vehicle_arrival;
  assign _066_[6] = gate_ack ? (* src = "./hdl/behavioral_parkingController.v:100.21-100.29|./hdl/behavioral_parkingController.v:100.17-101.42" *) 1'h1 : 1'hx;
  assign _066_[11] = gate_ack ? (* src = "./hdl/behavioral_parkingController.v:100.21-100.29|./hdl/behavioral_parkingController.v:100.17-101.42" *) 1'h0 : 1'hx;
  assign _066_[15] = vehicle_left ? (* src = "./hdl/behavioral_parkingController.v:90.21-90.33|./hdl/behavioral_parkingController.v:90.17-93.20" *) 1'h0 : 1'hx;
  assign _066_[16] = vehicle_left ? (* src = "./hdl/behavioral_parkingController.v:90.21-90.33|./hdl/behavioral_parkingController.v:90.17-93.20" *) _074_[4] : 1'hx;
  assign _066_[17] = vehicle_left ? (* src = "./hdl/behavioral_parkingController.v:90.21-90.33|./hdl/behavioral_parkingController.v:90.17-93.20" *) vehicle_arrival : 1'hx;
  assign _066_[19] = code_ack ? (* src = "./hdl/behavioral_parkingController.v:77.21-77.30|./hdl/behavioral_parkingController.v:77.17-83.20" *) 1'hx : _000_;
  assign _066_[22] = code_ack ? (* src = "./hdl/behavioral_parkingController.v:77.21-77.30|./hdl/behavioral_parkingController.v:77.17-83.20" *) 1'hx : 1'h0;
  assign _066_[23] = code_ack ? (* src = "./hdl/behavioral_parkingController.v:77.21-77.30|./hdl/behavioral_parkingController.v:77.17-83.20" *) 1'hx : _001_;
  assign _063_[2] = code_ack ? (* src = "./hdl/behavioral_parkingController.v:77.21-77.30|./hdl/behavioral_parkingController.v:77.17-83.20" *) 1'hx : _070_[0];
  assign _063_[3] = code_ack ? (* src = "./hdl/behavioral_parkingController.v:77.21-77.30|./hdl/behavioral_parkingController.v:77.17-83.20" *) 1'hx : _071_[1];
  assign _066_[26] = vehicle_left ? (* src = "./hdl/behavioral_parkingController.v:70.21-70.33|./hdl/behavioral_parkingController.v:70.17-73.20" *) 1'h0 : _002_[2];
  assign _066_[27] = vehicle_left ? (* src = "./hdl/behavioral_parkingController.v:70.21-70.33|./hdl/behavioral_parkingController.v:70.17-73.20" *) 1'h0 : _002_[3];
  assign _066_[29] = vehicle_left ? (* src = "./hdl/behavioral_parkingController.v:70.21-70.33|./hdl/behavioral_parkingController.v:70.17-73.20" *) 1'h0 : _002_[5];
  assign _002_[2] = code_ack ? (* src = "./hdl/behavioral_parkingController.v:64.21-64.29|./hdl/behavioral_parkingController.v:64.17-67.20" *) _061_ : 1'hx;
  assign _002_[3] = code_ack ? (* src = "./hdl/behavioral_parkingController.v:64.21-64.29|./hdl/behavioral_parkingController.v:64.17-67.20" *) _062_ : 1'hx;
  assign _002_[5] = code_ack ? (* src = "./hdl/behavioral_parkingController.v:64.21-64.29|./hdl/behavioral_parkingController.v:64.17-67.20" *) 1'h0 : 1'hx;
  assign _066_[31] = vehicle_arrival ? (* src = "./hdl/behavioral_parkingController.v:59.21-59.36|./hdl/behavioral_parkingController.v:59.17-60.41" *) 1'h1 : 1'hx;
  assign _066_[35] = vehicle_arrival ? (* src = "./hdl/behavioral_parkingController.v:59.21-59.36|./hdl/behavioral_parkingController.v:59.17-60.41" *) 1'h0 : 1'hx;
  assign blocked_gate = _009_ ? (* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16" *) 1'h0 : _000_;
  assign close_gate = ~(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16" *) _025_;
  assign wrong_ping = _009_ ? (* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16" *) 1'h0 : _001_;
  assign open_gate = ~(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16" *) _026_;
  assign next_state[0] = _073_ ? (* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.25" *) _069_[0] : 1'h1;
  assign next_state[1] = _073_ ? (* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.25" *) _069_[1] : 1'h0;
  assign next_state[2] = _073_ ? (* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.25" *) _069_[2] : 1'h0;
  assign next_state[3] = _073_ ? (* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.25" *) _069_[3] : 1'h0;
  assign next_state[4] = _073_ ? (* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.25" *) _069_[4] : 1'h0;
  assign next_state[5] = _073_ ? (* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.25" *) _069_[5] : 1'h0;
  assign next_attempt[0] = _072_ ? (* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.25" *) _064_[2] : 1'h0;
  assign next_attempt[1] = _072_ ? (* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:597.13-597.25" *) _064_[3] : 1'h0;
  assign _004_ = ~(* src = {0{1'b0}} *) _065_[0];
  assign _067_[31] = _066_[31] &(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _068_[5];
  assign _067_[35] = _066_[35] &(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _068_[5];
  assign _067_[29] = _066_[29] &(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _068_[4];
  assign _067_[26] = _066_[26] &(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _068_[4];
  assign _067_[27] = _066_[27] &(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _068_[4];
  assign _067_[19] = _066_[19] &(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _065_[1];
  assign _067_[22] = _066_[22] &(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _065_[1];
  assign _067_[23] = _066_[23] &(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _065_[1];
  assign _067_[15] = _066_[15] &(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  open_gate;
  assign _067_[16] = _066_[16] &(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  open_gate;
  assign _067_[17] = _066_[17] &(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  open_gate;
  assign _067_[6] = _066_[6] &(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  close_gate;
  assign _067_[11] = _066_[11] &(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  close_gate;
  assign _064_[2] = _063_[2] &(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _065_[1];
  assign _064_[3] = _063_[3] &(* src = "./hdl/behavioral_parkingController.v:0.0-0.0|./hdl/behavioral_parkingController.v:56.9-120.16|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:585.44-585.84" *)  _065_[1];
  assign _071_[1] = attempt[1] ^(* src = "./hdl/behavioral_parkingController.v:78.43-78.58|/home/roger/gitRepos/yosys/oss-cad-suite/lib/../share/yosys/techmap.v:289.13-289.25" *)  attempt[0];
  assign { _002_[4], _002_[1:0] } = { _002_[5], _002_[5], _002_[5] };
  assign _039_[2] = _037_[2];
  assign _041_[2:1] = { _037_[2], _039_[1] };
  assign _044_[1:0] = { _039_[1], _037_[0] };
  assign _046_[1:0] = { _039_[1], _037_[0] };
  assign { _047_[2], _047_[0] } = { _037_[2], _037_[0] };
  assign _049_[0] = _067_[11];
  assign { _051_[2], _051_[0] } = { _049_[2], _067_[11] };
  assign _053_[0] = _067_[11];
  assign _055_[1:0] = { _053_[1], _067_[11] };
  assign _056_[0] = _067_[11];
  assign { _059_[2], _059_[0] } = _034_;
  assign _063_[1:0] = 2'hx;
  assign _064_[1:0] = 2'h0;
  assign { _066_[34:32], _066_[30], _066_[28], _066_[25:24], _066_[21:20], _066_[18], _066_[14:12], _066_[10:7], _066_[5:0] } = { _066_[35], _066_[35], _066_[35], _066_[35], _066_[29], _066_[29], _066_[29], _066_[22], _066_[22], _066_[22], _066_[15], _066_[15], _066_[15], _066_[11], _066_[11], _066_[11], _066_[11], 6'hxx };
  assign { _067_[34:32], _067_[30], _067_[28], _067_[25:24], _067_[21:20], _067_[18], _067_[14:12], _067_[10:7], _067_[5:0] } = { _067_[35], _067_[35], _067_[35], _067_[35], _067_[29], _067_[29], _067_[29], _067_[22], _067_[22], _067_[22], _067_[15], _067_[15], _067_[15], _067_[11], _067_[11], _067_[11], _067_[11], 6'h00 };
  assign _068_[3:1] = { _065_[1], open_gate, close_gate };
  assign _070_[1] = attempt[1];
  assign _071_[0] = _070_[0];
  assign { _074_[5], _074_[3:0] } = { vehicle_arrival, 4'h0 };
endmodule
